### PR TITLE
Change `data-count` to `data-level` to match github's new HTML

### LINKED ISSUE #42: Github HTML has changed, which breaks this project
Hey! This project is a downstream dependency for [githubchart](https://github.com/akerl-archived/githubchart), which in turn is a dependency for [githubchart-api](https://github.com/2016rshah/githubchart-api). I believe the entire chain has been broken because I think github changed their HTML that we scrape from. In particular, I believe the svg used to have a field called `data-count` which no longer exists. This is causing the data structure to be undefined, which breaks everything. 

I'm not super familiar with this part of the codebase. Would you possibly be able to update this line based on the updated github HTML @akerl ?

https://github.com/akerl-archived/githubstats/blob/8a2c91ce712f03182640ae00c989551fc0dfe100/lib/githubstats.rb#L148

In case it is helpful, this is what the HTML looks like nowadays:

```
<rect width="11" height="11" x="16" y="0" class="ContributionCalendar-day" data-date="2022-01-02" data-level="0" rx="2" ry="2">No contributions on January 2, 2022</rect>
```

### PR DESCRIPTION
**Pull request by 2016rshah**
This is my best guess of how to fix the repository. I would appreciate a second set of eyes to confirm I didn't break anything/actually fixed the problem based on Github's new HTML before merging. 

Fixes #42

### CODE REVIEW

**Comment by akerl** [comment]
Seems right to me. Thanks for submitting!

**Comment by 2016rshah** [comment]
Sorry I'm not super familiar with publishing Ruby gems. Don't we also need to increment the version number of this gem, and change the gem files of down stream dependencies (like githubchart) so the changed code gets propagated? Or is there a simpler way to get the changes?

**Comment by akerl** [comment]
Yup. Was mostly mobile yesterday, needed to do some cleanup to get the repo building again, since I've moved around how my builds run since the last time

**Comment by akerl** [comment]
GithubStats 3.3.0 and GithubChart 3.4.0 released!

**Comment by 2016rshah** [comment]
Incredible, thank you so much! Works like a charm :)

**Pull request merged**
